### ISSUE TITLE
Failed to parse XML document

### ISSUE THREAD

**Issue by georgeOsdDev** [georgeOsdDev/xitrum-leochat#13]
This error occur when application access LeoFS(0.14.9) with AWS-SDK(1.6.2).
- Reprpduce flow : https://gist.github.com/georgeOsdDev/7190154#file-from-repl
- Error Log : https://gist.github.com/georgeOsdDev/7190154#file-scla-error-log
- TCP DUMP : https://gist.github.com/georgeOsdDev/7190154#file-tcpflow-dump
  `sudo tcpflow -c -i lo0 src or dst host localhost`

TCP dump(https://gist.github.com/georgeOsdDev/7190154#file-tcpflow-dump) seems to that LeoFS returns collect XML.
I can not determine whether it is the problem of compatibility of LeoFS or a bug in the SDK.

So I avoid this problem with adding patch to SDK 

https://github.com/georgeOsdDev/xitrum-leochat/blob/master/lib/XmlResponsesSaxParser.java#L621

See also https://gist.github.com/georgeOsdDev/7190154

**Comment by yosukehara** [comment]
We've found the issue of Java's S3 lib - https://github.com/leo-project/leofs/issues/94#issuecomment-28365422
So we will resolve leofs-related codes.

**Comment by georgeOsdDev** [comment]
leo-project/leo_gateway@8e60acf
